#!/usr/bin/env bash
# Installs the shared Content AI assets (skills, subagents, always-on guardrails)
# from CM-AI-Content-Skills into a target portal with APM, the only distribution
# path that repository supports (see its docs/consuming.md).
#
# Two modes, decided by the portal:
#   - The portal commits its own apm.yml: it is honored as-is (apm install --frozen
#     when apm.lock.yaml exists), and the deployed tree is the portal's to commit.
#   - No apm.yml: a git-excluded manifest is generated that points at the local
#     CM-AI-Content-Skills checkout (or CONTENT_AI_APM_DEPENDENCY), and everything
#     APM writes is kept out of the portal's Git status.
set -euo pipefail

TARGET_WORKSPACE="${1:-${CONTENT_AI_TARGET_WORKSPACE:-$PWD}}"
if [ -z "${CONTENT_AI_WORKSPACE_ROOT:-}" ]; then
  echo "[sync-content-ai-assets][warning] CONTENT_AI_WORKSPACE_ROOT is not set; defaulting the repositories parent folder to /workspaces." >&2
  CONTENT_AI_WORKSPACE_ROOT="/workspaces"
fi
CONTENT_AI_ROOT="${CONTENT_AI_REPO_PATH:-$CONTENT_AI_WORKSPACE_ROOT/CM-AI-Content-Skills}"
CONTENT_AI_APM_VERSION="${CONTENT_AI_APM_VERSION:-v0.31.0}"
CONTENT_AI_APM_DEPENDENCY="${CONTENT_AI_APM_DEPENDENCY:-}"
CONTENT_AI_APM_INSTALL_CLI="${CONTENT_AI_APM_INSTALL_CLI:-true}"
GENERATED_MARKER="Generated by sync-content-ai-assets.sh"

log() { echo "[sync-content-ai-assets] $*"; }
warn() { echo "[sync-content-ai-assets][warning] $*" >&2; }
fail() { echo "[sync-content-ai-assets][error] $*" >&2; exit 1; }

[ -d "$TARGET_WORKSPACE" ] || fail "Target workspace was not found: $TARGET_WORKSPACE"

if [ -z "$CONTENT_AI_APM_DEPENDENCY" ]; then
  if [ ! -d "$CONTENT_AI_ROOT/.apm" ] || [ ! -f "$CONTENT_AI_ROOT/apm.yml" ]; then
    fail "Shared Content AI assets were not found at $CONTENT_AI_ROOT (expected a CM-AI-Content-Skills checkout with .apm/ and apm.yml). Set CONTENT_AI_REPO_PATH, or CONTENT_AI_APM_DEPENDENCY to a published pin such as jpsmoreira-com/CM-AI-Content-Skills#v1.0.0."
  fi
  CONTENT_AI_APM_DEPENDENCY="$(cd "$CONTENT_AI_ROOT" && pwd)"
fi

export PATH="$HOME/.local/bin:$PATH"
ensure_apm_cli() {
  if command -v apm >/dev/null 2>&1; then
    return 0
  fi
  if [ "$CONTENT_AI_APM_INSTALL_CLI" != "true" ]; then
    fail "The apm CLI is not on PATH and CONTENT_AI_APM_INSTALL_CLI=$CONTENT_AI_APM_INSTALL_CLI. Install it: curl -sSL https://aka.ms/apm-unix | sh -s -- @$CONTENT_AI_APM_VERSION"
  fi
  command -v curl >/dev/null 2>&1 || fail "curl is required to install the apm CLI."
  log "Installing the APM CLI $CONTENT_AI_APM_VERSION into $HOME/.local/bin"
  curl -sSL https://aka.ms/apm-unix | sh -s -- "@$CONTENT_AI_APM_VERSION"
  command -v apm >/dev/null 2>&1 || fail "The apm CLI is still not on PATH after installation."
}
ensure_apm_cli
log "Using $(apm --version 2>/dev/null | head -n 1)"

cd "$TARGET_WORKSPACE"
git_dir=""
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git_dir="$(git rev-parse --absolute-git-dir)"
fi

is_tracked() {
  [ -n "$git_dir" ] && git ls-files --error-unmatch "$1" >/dev/null 2>&1
}

add_git_excludes() {
  [ -n "$git_dir" ] || return 0
  mkdir -p "$git_dir/info"
  touch "$git_dir/info/exclude"
  local entry
  for entry in "$@"; do
    grep -qxF "$entry" "$git_dir/info/exclude" || printf "\n%s\n" "$entry" >> "$git_dir/info/exclude"
  done
}

# apm install appends a comment plus apm_modules/ to .gitignore (creating the file
# when absent). apm_modules/ is already git-excluded here, so a portal that has not
# adopted APM keeps its .gitignore untouched.
apm_gitignore_lines_only() {
  local line
  while IFS= read -r line; do
    case "$line" in
      ""|"# APM dependencies"|"apm_modules/") ;;
      *) return 1 ;;
    esac
  done
  return 0
}

restore_gitignore() {
  [ -n "$git_dir" ] || return 0
  case "$gitignore_state" in
    absent)
      if [ -f .gitignore ] && ! is_tracked .gitignore && apm_gitignore_lines_only < .gitignore; then
        rm -f .gitignore
      fi
      ;;
    clean)
      if ! git diff --quiet -- .gitignore \
        && [ "$(git diff --numstat -- .gitignore | awk '{print $2}')" = "0" ] \
        && git diff -- .gitignore | grep '^+' | grep -v '^+++' | sed 's/^+//' | apm_gitignore_lines_only; then
        git checkout -- .gitignore
      fi
      ;;
  esac
}

remove_legacy_layout() {
  # Leftovers of the pre-APM contract (namespaced copy plus dotagents). Only
  # material this script generated is removed; portal-authored files are kept.
  local legacy_copy=".agents/content-ai"
  if [ -f AGENTS.md ] && ! is_tracked AGENTS.md && [ -f "$legacy_copy/AGENTS.md" ] && cmp -s AGENTS.md "$legacy_copy/AGENTS.md"; then
    rm -f AGENTS.md
    log "Removed the legacy managed root AGENTS.md so apm compile can generate it."
    if [ -f "$legacy_copy/backups/AGENTS.md.before-content-ai-sync" ]; then
      cp -a "$legacy_copy/backups/AGENTS.md.before-content-ai-sync" AGENTS.md
      log "Restored the portal's original AGENTS.md from the legacy backup."
    fi
  fi
  if [ -n "$git_dir" ] && is_tracked AGENTS.md && git ls-files -v AGENTS.md | grep -q '^S'; then
    git update-index --no-skip-worktree AGENTS.md
    git checkout -- AGENTS.md
    log "Restored the tracked AGENTS.md that the legacy sync had overwritten."
  fi
  if [ -d "$legacy_copy" ]; then
    rm -rf "$legacy_copy"
    log "Removed the legacy $legacy_copy copy."
  fi
  if [ -f agents.toml ] && grep -q "$GENERATED_MARKER" agents.toml; then
    rm -f agents.toml agents.lock
    log "Removed the generated dotagents manifest."
  fi
}
remove_legacy_layout

portal_name="$(basename "$TARGET_WORKSPACE" | tr -c 'A-Za-z0-9._-' '-' | sed 's/^-*//; s/-*$//')"
generated_manifest=false
if [ ! -f apm.yml ] || grep -q "$GENERATED_MARKER" apm.yml; then
  generated_manifest=true
  cat > apm.yml <<MANIFEST
# $GENERATED_MARKER - not committed (see .git/info/exclude).
# A portal that adopts the shared assets should commit its own apm.yml pinned to a
# CM-AI-Content-Skills release tag (see that repository's examples/apm.yml); this
# generated file then stops being written.
name: ${portal_name:-docs-portal}
version: 0.1.0
targets:
  - copilot
  - claude
  - codex
dependencies:
  apm:
    - $CONTENT_AI_APM_DEPENDENCY
  mcp: []
MANIFEST
  log "Generated a local apm.yml pointing at $CONTENT_AI_APM_DEPENDENCY"
else
  log "Using the portal's committed apm.yml"
fi

gitignore_state="dirty"
if [ ! -e .gitignore ]; then
  gitignore_state="absent"
elif is_tracked .gitignore && git diff --quiet -- .gitignore; then
  gitignore_state="clean"
fi

if [ "$generated_manifest" = false ] && [ -f apm.lock.yaml ]; then
  if ! apm install --frozen; then
    warn "apm install --frozen failed (apm.yml and apm.lock.yaml disagree?); running apm install."
    apm install
  fi
else
  apm install
fi

compile_log="$(mktemp)"
apm compile 2>&1 | tee "$compile_log"
if grep -q "Protected AGENTS.md" "$compile_log"; then
  warn "AGENTS.md is hand-authored, so the shared guardrails were not compiled into it (Codex reads only AGENTS.md). Move the portal rules to .apm/instructions/<name>.instructions.md and delete AGENTS.md; see CM-AI-Content-Skills docs/consuming.md."
fi
rm -f "$compile_log"

if [ "$generated_manifest" = true ]; then
  add_git_excludes "/apm.yml" "/apm.lock.yaml" "apm_modules/" "/.agents/" "/.claude/skills/" "/.claude/agents/" "/.claude/rules/" "/.codex/agents/" "/.github/agents/" "/.github/instructions/" "/.github/copilot-instructions.md"
  if [ -f AGENTS.md ] && ! is_tracked AGENTS.md; then
    add_git_excludes "/AGENTS.md"
  fi
  restore_gitignore
fi

log "Shared Content AI assets installed into $TARGET_WORKSPACE (skills: .agents/skills and .claude/skills; subagents: .github/agents, .claude/agents, .codex/agents; guardrails: .github/instructions, .claude/rules, AGENTS.md)."
